spring:
  datasource:
    url: jdbc:h2:file:./data/localdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com._uthz.api_server: DEBUG
    org.springframework: DEBUG