spring:
  application:
    name: api-server
  profiles:
    active: local

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  access:
    expiration: 86400000  # 24 hours in milliseconds
  refresh:
    expiration: 604800000  # 7 days in milliseconds

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
    displayRequestDuration: true
    showCommonExtensions: true