spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_server
    username: ${DB_USERNAME:api_user}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active: prod

logging:
  level:
    com._uthz.api_server: INFO
    org.springframework: WARN